INSERT INTO CATEGORY (description) VALUES ('American');
INSERT INTO CATEGORY (description) VALUES ('Italian');
INSERT INTO CATEGORY (description) VALUES ('Mexican');
INSERT INTO CATEGORY (description) VALUES ('Fast Food');
INSERT INTO CATEGORY (description) VALUES ('Chinese');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Teaspoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Tablespoon');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Cup');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Pinch');
INSERT INTO UNIT_OF_MEASURE (description) VALUES ('Dash');
